### ISSUE TITLE
Integer ('long') overflow in calculated 5-byte date/time values.

### ISSUE THREAD

**Issue by gtoal** [hamishcoleman/riscose#2]
Building the emulator failed due to an overflow error detected by gcc at compile time. (presumably an error that wasn't checked for when this code was released).  I don't know if I fixed it correctly so please check this before adding it.  The fix was basically to use "long long" rather than "long" for the critical variable.  The casting and ULL constants may not be strictly necessary but I still remember the "ANSI Surprise!" error messages from Norcroft C so I've always erred on the side of caution when performing shifts in C.  By the way given that the Norcroft C for Acorn sources have now been posted online perhaps you might change the original Riscose author's policy of not including the C compiler in the test files?

[osfile.c.patch](https://github.com/hamishcoleman/riscose/files/13046931/osfile.c.patch)

**Comment by davel** [comment]
Hello,

Thank you again, I have merged this. I suspect you're seeing this error and I am not because you're using a 32 bit host. I have thus patched the code to use a `uint64_t` type, which hopefully does the correct thing on all platforms.

I didn't know that Norcroft C is open source, do you have a reference? It was still being sold for money last time I looked. I am trying to decide about adding real RISC OS binaries. Current versions of RISC OS itself are BSD licensed, but things like SharedCLibrary and old BASIC binaries remain closed source. Perhaps the solution is to keep the abandonwares in a separate repository?

If it's easier, feel free to email me patches directly or even using `git-format-patch` etc.

Cheers,
Dave
